services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_USER: lucamazzarello_
      POSTGRES_PASSWORD: proyectotd8
      POSTGRES_DB: ONWIP
    ports:
      - 5433:5432
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build:
      context: .
      args:
        - PROCESS_PDFS=${PROCESS_PDFS:-false}
    volumes:
      - ./data:/app/pdfs
    ports:
      - "3000:3000"
    image: onwy
    environment:
      NODE_ENV: development
      PROCESS_PDFS: ${PROCESS_PDFS}
    develop:
      watch: 
        - action: sync
          path: ./Chatbot2.0
          target: /app/Chatbot2.0 
          ignore:
            - node_modules/
        - action: rebuild
          path: package.json

volumes:
  pgdata:
